# Generated by Django 4.2.7 on 2024-01-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSRP', '0002_topic_info_host_message_info_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
