# Generated by Django 4.2.7 on 2024-01-26 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FSRP', '0005_rename_image_profile_profile_pic_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
