# Generated by Django 4.2.7 on 2024-02-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSRP', '0007_soil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='nitrogen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soil',
            name='ph',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soil',
            name='phosphorous',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soil',
            name='potassium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soil',
            name='rainfall',
            field=models.IntegerField(default=0),
        ),
    ]
