# Generated by Django 4.2.7 on 2024-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSRP', '0008_alter_soil_nitrogen_alter_soil_ph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='nitrogen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='soil',
            name='ph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='soil',
            name='phosphorous',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='soil',
            name='potassium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='soil',
            name='rainfall',
            field=models.FloatField(),
        ),
    ]
