# Generated by Django 4.2.7 on 2024-02-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSRP', '0009_alter_soil_nitrogen_alter_soil_ph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
