# Generated by Django 4.2.7 on 2024-02-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSRP', '0010_profile_lat_profile_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soil',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soil',
            name='phosphorous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soil',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soil',
            name='rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
